### ISSUE TITLE
Parser not found

### ISSUE THREAD

**Issue by edvinasnet** [opendatasoft/elasticsearch-aggregation-geoclustering#1]
After installing aggregation new gets elastic search error:

"reason": "[1:46] unable to parse BaseAggregationBuilder with name [geohash_clustering]: parser not found"

I am posting :
`{
  "aggregations": {
    "agg": {
      "geohash_clustering": {
        "field": "coordinates",
        "zoom": "1"
      }
    }
  }
}`

what is the problem?

My elastic version:
`"version": {
"number": "6.4.1",
"build_flavor": "oss",
"build_type": "tar",
"build_hash": "e36acdb",
"build_date": "2018-09-13T22:18:07.696808Z",
"build_snapshot": false,
"lucene_version": "7.4.0",
"minimum_wire_compatibility_version": "5.6.0",
"minimum_index_compatibility_version": "5.0.0"
},`

**Comment by clement-tourriere** [comment]
Thank you very much for testing this plugin.
In fact there is an error in documentation. The plugin name is in fact: `geo_point_clustering`.
I'm updating the documentation.
