### ISSUE TITLE
Works as expected on elastic.co clusters?

### ISSUE THREAD

**Issue by trescube** [opendatasoft/elasticsearch-aggregation-geoclustering#13]
(this isn't so much an issue as it is a question for confirmation)

We're planning to switch our elasticsearch hosting to elastic.co (or similar) and looking for confirmation that this plugin runs with little or no difficulty on elastic.co-hosted clusters.   This plugin's functionality is the reason we're switching away from AWS OpenSearch and, while I'm personally confident that it will run as expected, management would really like some external (even anecdotal) confirmation during our due diligence phase that this works.  

While I would happily test this myself on our test elastic.co cluster, plugins are not available with the free tier or even monthly subscriptions, they're only available with annual contracts (which we'll switch to once confirmed, we're avoiding during the evaluation phase for cost reasons).  

I have this plugin running locally in docker with Elasticsearch 7.17.6 (and it works great!) so any feedback on operability or gotchas would be greatly appreciated.

**Comment by mhugo** [comment]
Hi,
Thanks for using our plugin. We do not host our Elasticsearch clusters on elastic.co, so we won't be able to confirm. But I cannot see any reason why it could not work. Maybe you could ask Elastic to confirm that it will work on their infrastructure, especially if it's the main reason you're switching from OpenSearch and are ready to pay for an annual contract :)

**Comment by trescube** [comment]
We do have a question out to them about this and are hoping that their response is truthful!

**Comment by trescube** [comment]
Confirmed that this works as expected in hosting via elastic.co, closing.
